### ISSUE TITLE
mdbx.h: conflicting declaration of mode_t

### ISSUE THREAD

**Issue by zingchen** [leo-yuriev/libmdbx#15]
In "mdbx.h", the declaration

`typedef unsigned mode_t; `

conflicts with the declaration of the same type in <sys/types.h>

`typedef _mode_t mode_t;`

The error was detected by GCC 7.1 (Mingw-w64) on Windows 7 - x64.

Changing the conflicting declaration to

`typedef unsigned short mode_t; `

seems to compile.

**Comment by leo-yuriev** [comment]
@zingchen , thanks for reporting.
I will fix this.
But I don't recommend use GCC/MinGW under Windows, since just not tested.

**Comment by zingchen** [comment]
MinGW is fine, at least for (tiny) programs I've done. I use it as it integrates well with Code::Blocks, a mature IDE and lighter, faster than MSVC.

**Comment by leo-yuriev** [comment]
@zingchen, no problem. Just report a bugs, if ones.
