### ISSUE TITLE
osal.c mdbx_panic error: #error FIXME

### ISSUE THREAD

**Issue by zingchen** [leo-yuriev/libmdbx#16]
A compilation error `#error FIXME` was detected in "osal.c" function `__cold void mdbx_panic(...)` by MinGW GCC 7.1 on Windows 7 - x64.

I think it's because the relevant code fragment
```
if (IsDebuggerPresent()) {
    OutputDebugString("\r\n" FIXME "\r\n");
    FatalExit(ERROR_UNHANDLED_ERROR);
}
```

is defined only under `#ifdef _MSC_VER`, which is not true in this environment. But I'm not sure.

**Comment by leo-yuriev** [comment]
@zingchen , today I am on the road, so the problem will fix later.

**Comment by leo-yuriev** [comment]
@zingchen, I got home and assessed the volume of work.
It's more than I expected. Think I can do this not earlier in the end of weekend.

**Comment by zingchen** [comment]
I see. There're several other FIXMEs that seem to be MinGW-relevant too.

**Comment by leo-yuriev** [comment]
I am sorry.

**Comment by leo-yuriev** [comment]
@zingchen, on the other hand - you could make this work and submit a pull-request. In this case _please_ don't forget about testing (i.e. appveyor.yml). So, at least one more set of test cases must be implemented:
 - validation of cleanup on thread termination (and so on), with respect to glibc bugs #21031 and #21032.
 - validation of interoperability with libmdbx.dll and libmdbx.lib, which were built by MSVC 2013/2015/2017.

Related to https://github.com/leo-yuriev/libmdbx/issues/17
