### ISSUE TITLE
Последние наработки по LSM

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [leo-yuriev/libmdbx#18]
Не знаю по адресу или нет.
Я тут наткнулся на такое обсуждение
https://forum.golangbridge.org/t/leveldb-written-in-go-build-from-scratch/4431
В итоге этот чел сделал своё хранилище: https://github.com/dgraph-io/badger
Основывается оно на последних наработках по LSM (как я понял из ридми у libmdbx LSM тоже используется):
https://www.usenix.org/system/files/conference/fast16/fast16-papers-lu.pdf
Судя по тому что у него получилось
https://blog.dgraph.io/post/badger/
Барсук порвал RocksDB.
А RocksDB одна из быстрых хранилищ судя по этим тестам: 
https://www.influxdata.com/benchmarking-leveldb-vs-rocksdb-vs-hyperleveldb-vs-lmdb-performance-for-influxdb/

Может будет полезным, если не в курсе.

**Comment by leo-yuriev** [comment]
@0x4E69676874466F78, пока есть время и желание отвечу подробнее:

1. В libmdbx нет следов LMS, также как в LMDB.
 libmdbx является развитием LMDB, отличия описаны в README.

2. Все быстрые key-value движки ориентированны на подмножество сценариев, в которых выигрывают, проигрывая в других (универсальные проигрывают везде). Поэтому к бенчмаркам key-value движков следует относиться очень осторожно. К сожалению, подавляющее большинство тестов сводится к натягиваю "совы на глобус", с "внезапным" умалчиванием деталей и констатированием результатов ([типичный пример](https://www.influxdata.com/benchmarking-leveldb-vs-rocksdb-vs-hyperleveldb-vs-lmdb-performance-for-influxdb/)).

3. Теоретически движки с использование LSM будут иметь преимущества перед libmdbx когда:
   - данных больше доступного объема RAM.
   - сценарии использования предполагают выгоду от последовательной обработки чанков данных на HDD, в том числе когда данные хорошо сжимаемы и LSM-движок этим пользуется.
   - последние (недавно добавленные/обновленные) данные используются чаще.

4. В свою очередь limdbx будет превосходить других в своих целевых сценариях использования:
   - данные помещаются в RAM, либо выборки/обновления случайны.
   - предлагаемые режимы durability подходят, либо требуется быстрая готовность после аварии (отсутствие фазы восстановления).
   - могут быть получены дополнительные выгоды от zero-copy и MVCC.

5. В [README](https://github.com/leo-yuriev/libmdbx/blob/master/README.md) есть результаты бенчмарков со ссылкой на исходный код (т.е. могут быть проверены).
   - эти результаты уже устарели (новые должны быть лучше), так как libmdbx уже поддерживает авто-компактификацию (не имеет отношения к LSM) и имеет существенные изменения в пути фиксации данных на диске (три мета-страницы вместо двух).
   - тем не менее, на эти результаты можно ориентироваться, но ОБЯЗАТЕЛЬНО с учетом подробностей о сценариях тестирования (есть достаточно подробное описание выполняемых действий).
   - при интерпретации результатов (в том числе других тестов) нужно обязательно учитывать выбранный уровень/режим durability для данных, а также объем recovery после аварии.

**Comment by leo-yuriev** [comment]
Если говорить о дизайне **badger** и пояснениях автора о причинах, то я много не понимаю:

1. Проблемы с high write load: 
   - BoltDB сделан по мотивам LMDB, т. е. это LMDB реализованная на Go. В свою очередь в LMDB (и тем более в libmdbx) нет проблем с «high write load» (но будут проблемы с IOPS при полной фиксации каждой мелкой транзакции на HDD).
   - Однако, в MVCC+COW не все просто и много неочевидных моментов (например lifo-reclaiming в libmdbx), соответственно я не исключаю недочетов в BoltDB.
   - Поэтому проблемы с «high load write» в BoltDB/LMDB я отношу на дефекты в BoltDB, либо на неумение использовать BoldDB/LMDB. 

2. Я бы не назвал LSM подходящим выбором для графовой БД, только для отдельных специфичных сценариев:
   - LSM достаточно плох при случайных запросах, особенно плохо c latency.
   - любой запрос может привести к вынужденному "drill down" в LSM-дереве.
   - соответственно, это будет нормально работать только для специфических сценариев, либо при допустимости всплесков latency (на 4 и более порядков).

3. Для графовой ДБ (включая RDF и triplestore) не так важен опорный key-value движок, сколько исполнитель запросов, который будет максимально выгодно эксплуатировать любые свойства опорного движка.
   - Грубо говоря, быстрая точечная выборка отдельных key-value пар или мега-быстрая итерация ключей - мало что дадут без соответствующих реврайтера/планировщика/исполнителя запросов.
   - С другой стороны, графовая база не обязана обрабатывать все виды запросов, тем более делать это быстро. Как правило требуется адекватно-быстрого выполнения некоторого очень небольшого подмножества SPARQL/SPIN.
   - Думаю, что badger/dgraph -- нишевое решение, которое неплохо себя ведет в некоторых сценариях использования.

Короче, в целом я сильно сомневаюсь, что (к примеру) badger сможет выдержать хотя-бы 10% нагрузки, которую держит libmdbx в МегаФон (в составе ReOpenLDAP) без выбросов latency. Это без учета обстоятельства что в badger нет транзакций и непонятно что с durability и recovery.

Конечно хотелось-бы взять и измерить, но встраиваемые движки на разных языках сложно сравнивать.

**Comment by 0x4E69676874466F78** [comment]
> В libmdbx нет следов LMS, также как в LMDB.

Меня просто сбило с толку это предложение

> использованное место на диске при завершении теста, после закрытия БД из тестирующего процесса, но без ожидания всех внутренних операций обслуживания (компактификации LSM и т.п.).

увидел упоминание и показалось что есть следы. Теперь понял что это касается только тех движков где такой механизм есть.
В базах на низком уровне пока плохо разбираюсь чтоб делать правильные выводы. 

Спасибо за столь развёрнутое пояснение, это интересно и полезно. 

А может знаете какие сейчас есть быстрые, сравнительно удобные и достаточно надёжные графовые бд? А то что я видел либо на Java (по статьям что мне попадались оно тормозное и люди переходили на psql), либо вот совсем новое типа dgraph сырое. Сам сейчас графы строю в postgresql, благо sql позволяет подобное (ещё видел корейский форк где приделали Cypher Query https://github.com/bitnine-oss/agensgraph ), хотя специального индекса под графы там нет, да и я не видел где-то такого, нашёл только GRIPP https://edoc.hu-berlin.de/handle/18452/3121 но не увидел чтобы он где-то использовался.

**Comment by leo-yuriev** [comment]
> А может знаете какие сейчас есть быстрые, сравнительно удобные и достаточно надёжные графовые бд?

Это риторический вопрос и вы не правильно ищете.

Вам нужно хорошо знать какие задачи и как вы собираетесь решать посредством графовой БД.
Затем понять, точнее оттранслировать это на методы решения задач и соответствующие "графовые" алгоритмы.
А далее понять какие свойства (включая индексы и прочее) вам нужны от графовой БД.

-----

Что касается "тормознутости" решений на Java, то есть объективные обстоятельства, причем как "плюсы", так и "минусы":
 - модель вычислений в java (виртуальная машина) всегда потребует накладных расходов на сложные структуры данных "на указателях" (но не на массивах).
 - java работает на "комбинировании абстракций и паттернов", что примерно всегда выражается в излишней надежде на сборщик мусора и прочие прелести, из-за этого примерно все java-решения укачивает большим объемом данных и/или высоким темпом операций.
- да, в итоге, Java всегда будет медленнее (не быстрее) решений на C/C++, но дешевле в разработке и в не-нагруженных остальных случаях может быть отличным средством.

Другими словами, отказываться от java нужно понимая зачем вы этом делаете.

**Comment by 0x4E69676874466F78** [comment]
> Вам нужно хорошо знать, какие задачи и как вы собираетесь решать посредством графовой БД.
Затем понять, точнее оттранслировать это на методы решения задач и соответствующие "графовые" алгоритмы.
А далее понять, какие свойства (включая индексы и прочее) вам нужны от графовой БД.

В развивающемся проекте это невозможно, поэтому ищется самое лучше из представленного, где в среднем уже (потенциально за счёт хорошей архитектуры) покрыто много случаев использования — достаточно гибкое и развитое на вырост, при этом выбирается наиболее быстрое решение относительного прочего, по крайней мере чтобы оно было не медленнее уже имеющегося (как в моём случае postgresql — можно попробовать заменить на другое из-за удобства или простоты в сложных запросах).
Мне достаточно названий я дальше сам поищу в сети инфу, на худой конец буду иметь ввиду и когда припрёт устрою тестирования на имеющихся случаях использования. Спрашиваю потому что заметил что не всё так просто гуглится. 



> Другими словами, отказываться от java нужно понимая зачем вы этом делаете.

Тот же Neo4J на яве медленнее даже имитации на postgres в обычном случае использования.
К тому же ява тащит зависимость в виде JVM, а ещё наверняка выжрет много памяти.

Вот тут в FAQ https://github.com/dgraph-io/dgraph/blob/master/wiki/content/faq/index.md
Даются ссылки на сравнения с dgraph:
> Every other graph system that we've run it against, Dgraph has been at least a 10x factor faster. It only goes up from there. But, that's anecdotal observations.
> Here are some actual benchmarks:
> * Dgraph against Neo4J – check [this blog post](https://open.dgraph.io/post/benchmark-neo4j/)
> * Dgraph against Cayley – check [this github repo](https://github.com/ankurayadav/graphdb-benchmarks#results-of-queries-benchmark) (credit to Ankur Yadav)

Как видно Нео там заметном в проигрыше как по скорости так и по жору памяти, Cayley c болтом тоже проигрывают.

Кстати в факе написано ещё почему они от болта отказались:
> Why doesn't Dgraph use BoltDB?
BoltDB depends on a single global <code>RWMutex</code> lock for all reads and writes; this negatively affects concurrency of iteration and modification of posting lists for Dgraph. For this reason, we decided not to use it and instead use RocksDB. On the other hand, RocksDB supports concurrent writes and is being used in production both at Google and Facebook.

**Comment by leo-yuriev** [comment]
Боюсь вы поняли что я хотел сказать и не приняли советы к использованию.

Графовая база - это buzzword. Вершины, дуги и их атрибуты можно хранить и обрабатывать сотней способов. В том числе в key-value, в колоночном виде или в традиционных реляционных таблицах и т.д.  и все это есть в СУБД, которые называют "графовыми".

Подобрать подходящую СУБД можно только исходя из достаточно детальных сценариев использования и массы других требований. Если вы не владеете компетенция. ми или не располагаете ресурсами, то будет просто играть в лотерею. С другой стороны, очень сложно знать все необходимое наперед, поэтому разведка боем - вполне подходящая тактика.

Примерно по тем-же причинам бенчмарки "Dgraph vs XYZ" у меня вызывают лишь подозрение и осторожность. Есть масса вещей, который при рассмотрении чуть под другим углом становятся минусами, а не плюсами. Например, "конкуррентное изменение и загрузка данных", в реальности обычно означает:
 - нет сериализации операций, нет ACID, поэтому одинаковые запросы могут возвращать разные результаты (как карты лягут).
 - масса ресурсов тратиться на разделение доступа или на разрешение конфликтов (когда обновления как-то пересекаются).
 - при крахе (аварии по питанию) СУБД может потерять все что угодно.

С другой стороны, действительно есть масса случаев когда достаточно "слабой консистенции" данных и перечисленные пункты работают в плюс. Тем не менее, я очень рекомендую хорошо ознакомиться с вопросами/ответами:
 - что дает seriazability и её отсутствие;
 - каких блокировок и заморочек стоит поддержка ACID и MVCC в традиционный СУБД.
 - почему Tarantool и Redis однопоточные (обрабатывают запросы в один поток).

Собственно для чего я это пишу - в подобных бенчмарках важно понимать "какую сову на какой глобус натягивали", насколько подходят сравниваемые СУБД для эмулируемых в бенчмарках задач, насколько оптимальны использованные опции/настройки, насколько адекватны использованные метрики и т.д.

-----

> BoltDB depends on a single global RWMutex lock for all reads and writes.

**Это не так**.

На самом деле читающие транзакции выполняются параллельно и никак не блокируются пишущими, при этом у каждого читателя консистентный снимок данных.

А вот "пишущие" транзакции действительно выполняются строго последовательно, что дает упомянутую сериализованность изменений и избавляет от массы проблем.

**Comment by 0x4E69676874466F78** [comment]
> Графовая база - это buzzword. Вершины, дуги и их атрибуты можно хранить и обрабатывать сотней способов. В том числе в key-value, в колоночном виде или в традиционных реляционных таблицах и т.д. и все это есть в СУБД, которые называют "графовыми".

Это мне понятно, у самого же графы хранятся в postgres который из коробки можно сказать ничего для удобства работы с графами не имеет. Я исхожу из того что специализированное (в данном случае тематика графы) будет лучше (т. к. решение специально создавалось/заточено под работу с графами), хотя смотря на тот же Neo4J понимаю что это далеко не всегда так, потому что много зависит от движка-хранилища от того насколько он хорошо оптимизирован (+ влияние реализации ЯП).

> Если вы не владеете компетенция. ми или не располагаете ресурсами, то будет просто играть в лотерею. С другой стороны, очень сложно знать все необходимое наперед, поэтому разведка боем - вполне подходящая тактика.

Не владею (достаточной), как и пока большими ресурсами. Но играть в лотерею тоже не хочу. Плохой старт может плохо сказаться на судьбе проекта (взять ту же монгу и сесть в лужу), поэтому ищу хотя бы не полное говно (по сравнению с другими решениями). Обычно я выбираю исходя из задачи (postgres был выбран как единственное решение где можно иметь быструю безсхемность (JSONB + индекс) при этом не терять особо в удобствах SQL), но сейчас задача по графам довольно размыта. 

Пока я могу сказать что мне нужно насколько возможно быстрое построение цепочек графов с каким-то условиями, ибо postgres это делает не столь быстро (ну грубо говоря находим один ключ, читаем значение, прыгаем на следующий ключ и т. д. вроде там индексы что-то помогают но насколько сильно я уже забыл, в любом случае это было заметно медленнее чем обычные запросы), без кэширования не обойтись.

Из условий например:
* Права доступа — не лезть внутрь графа где нет достаточных прав доступа (тут кстати кэш может начать распухать при индивидуальных правах, а граф может быть длинный, хорошим это вряд ли кончится). 
* Если представить граф как дерево (граф развивается сверху вниз как неориентированный), то пройтись быстро не только вниз по графу, но и наверх (от "дочернего" построить как кусок связанный только с ним до самого первого "родителя" — просто ветку, так и всё связанное дерево — с захватом соседних связанных нисходящих веток, иначе говоря поднимаясь вверх видя что на узел что-то ещё ссылается в сторону подгрузить и их).

Сейчас у меня по сути две таблицы, одна с узлами (данными, правами доступа), другая с рёбрами и флагом обозначающим что там есть права доступа. Тут для скорости я могу попробовать всячески изворотиться (пустить те узлы с флагами прав доступа в отдельном запросе и там соединить с таблицей где сами права доступа, и пока проверяются эти права доступа общий граф уже будет отдан), но всё это видится как-то стрёмно и кажется что специально заточенные графовые БД подобное решали бы более просто и производительнее. 
В голове крутится желание сделать так чтоб можно было сразу быстро получить весь нужный граф (только вниз, только вверх, во всех направлениях) и чтоб не хранить избыточную инфу (флаг прав доступа вынесен чтоб не дублировать длинные списки прав доступа для узлов ссылаемых на один и тот же узел). И вроде бегло подумав кажется что такую структуру вряд ли возможно сделать оптимально на текущем железе, но хотелка всё равно не пропадает.

Благодарю за ответы, редко выпадает возможность почитать подобное от специалиста.

**Comment by leo-yuriev** [comment]
Конечно, есть шанс, что в какой-нибудь "графовой" БД найдется что-нибудь существенно облегчающее решение вашей задачи.

Но вполне вероятно, что решение следует искать в другом направлении. И чем больше масштаб (объем данных и требуемая скорость), тем выше эта вероятность.

По-сути, СУБД занимается тем, что позволяет вам организованно читать/писать элементы данных используя логические адреса (ключи). Тем мельче элементы, тем изолированнее изменения и тем адреснее могут быть выборки. Однако, при этом растет кол-вол элементов, кол-во связей между ними и кол-во необходимых поиско-подобных операций.

В вашем случае вовсе не обязательно дробить все на вершины, ребра и их атрибуты. Такие мелкие элементы могут потребовать огромное кол-во операций, т. е. вы увязните в мышиной возне. Пожалуй это оправдано, только если требуется много точечных изменений отдельных элементов, и эти изменения требуется делать быстро (в ущерб остальному).

Соответственно, вовсе не обязательно использовать грффовые БД и оперировать в терминах графов (а вот мыслить можно в любых терминах  и моделях).

Рекомендую подумать над тем чтобы манипулировать некоторыми специализированными представлениями (срезами, проекциями).

**Comment by 0x4E69676874466F78** [comment]
> Пожалуй это оправдано, только если требуется много точечных изменений отдельных элементов, и эти изменения требуется делать быстро (в ущерб остальному).
Я стараюсь сделать архитектуру insert-only, чтобы в дальнейшем можно было без труда перейти на колоночный движок (по факту это просто совпадение-бонус версионирования, но я решил придерживаться этой концепции и в остальном). 

> Рекомендую подумать над тем чтобы манипулировать некоторыми специализированными представлениями (срезами, проекциями).
Я могу это истолковать двумя направлениями:
1. что-то в сторону OLAP (или подобного)
2. что-то самописное аля специализированные хранилища как том же вконтакте где простое-тупое как дрова но эффективное в своей задаче.
Первое я только узнал, а если раньше и видел то только вскользь, до второго же пока не дорос умениями чтобы делать эффективно. 
Как понимаю речь именно про первое. 
Спасибо, поизучаю. OLAP я смотрю ещё разных видов существует.

**Comment by leo-yuriev** [comment]
OLAP вам никак не поможет, совсем.

**Comment by 0x4E69676874466F78** [comment]
> OLAP вам никак не поможет, совсем.

А о чём тогда речь говоря о "некоторыми специализированными представлениями (срезами, проекциями)"?
Срезы и проекции оба понятия есть в OLAP. Другое я не нашёл.

**Comment by leo-yuriev** [comment]
OLAP манипулирует агрегатами и аккумуляторами - вам это малополезно

С другой стороны, внутри OLAP опирается на манипуляции с микро-кубами - отдельными кусками данных, для которых заранее вычисляется разумный набор агрегатов и аккумуляторов. Другими словами, после загрузки и "индексации" данных OLAP не просматривает и не анализирует отдельные исходные записи, так как их слишком много.

Вам нужно продумать свои "микро-кубы", чтобы уйти от большого кол-ва операций. Другими словами, вычислять что-то предварительно и хранить в БД не отдельные "вершины и дуги", а более крупные и удобные для дальнейших действий структуры.

**Comment by 0x4E69676874466F78** [comment]
Ну пока я думал в кэше хранить готовые графы, типа есть часто запрашиваемые родители и вот хранится всё что от него исходит, дальше чтоб не плодить повторов можно сначала проверять есть ли внутри уже уже нужный кусок графа и если есть то просто выдавать его срезом. Соответственно если что-то поменялось внутри графа то перестроить заново кусок в кэше. 
Но это просто костыль для производительности, да хорошо работает до тех пор пока не начинаются городиться те же права доступа, тут уже видимо придётся хранить уточнения которые надо проверять при формировании среза (доступны ли определённые куски пользователю или нет).
Ладно, спасибо за поучительную беседу и советы, буду потихоньку развиваться дальше.

**Comment by lostdj** [comment]
@0x4E69676874466F78

> postgres ... вроде там индексы что-то помогают но насколько сильно я уже забыл

? https://wiki.postgresql.org/wiki/Index-only_scans
В частности https://wiki.postgresql.org/wiki/Index-only_scans#Interaction_with_HOT

***

Вообще-то на LMDB много графовых обёрток наделали, но не знаю как они подходят под все требования с правами доступа и т.д.

**Comment by lostdj** [comment]
@0x4E69676874466F78 

> Ну пока я думал в кэше хранить готовые графы

Менеджить свой кэш -- всегда звучит жутко. Можно сразу держать ключи по схеме `rootid_childid`, создавая их сразу во время инсерта чайлда, или через duplicate keys со своим компаратором: http://www.lmdb.tech/doc/group__mdb.html#gacef4ec3dab0bbd9bc978b73c19c879ae

**Comment by leo-yuriev** [comment]
Теплее.
 Подумайте/посмотрите в сторону reasoning materialization, что примерно равнозначно "индексированию RDF". Ещё раз перечитайте тред.

**Comment by 0x4E69676874466F78** [comment]
@lostdj спасибо, закрою пробел и про бэкреференс учту, обёртки тоже гляну (не думал что они есть).
@leo-yuriev ещё раз спасибо, да, мозги начинают вправляться. Подниму матчасть и перечитаю, сейчас хватает пробелов.
На тему "выплыть не на ту строну", вспоминается piwik (аналитика в строковой БД) и такого действительно не хотелось бы.
