### ISSUE TITLE
Make libmdbx SWIG compatible

### ISSUE THREAD

**Issue by catroot** [leo-yuriev/libmdbx#27]
I've tried to bind libmdbx to python using swig with no success since mdbx.h contains not all nesessary definitions such as MDBX_env.
Can you make mdbx.h suitable to use with SWIG to produce correct output files?

When i tried to call the `mdbx.create_env(env)` from python i got:
`TypeError: in method 'mdbx_env_create', argument 1 of type 'MDBX_env **'`
But there is no way to obtain the MDBX_env ** type from as they are not imported by SWIG.

**Comment by leo-yuriev** [comment]
MDBX_env, MDBX_txn, MDBX_cursor and so on - are the internal structures and MUST NOT be defined outside libmdbx.
You should operate only opaque pointers to ones, no more.

Please read aboud opaque pointers in SWIG. For instance [#1](
https://github.com/swig/swig/wiki/FAQ#q-how-do-i-interact-with-functions-that-require-double-void-pointers---void-), [#2](http://jim-jotting.blogspot.ru/2014/08/swig-python-and-opaque-structs.html).
