### ISSUE TITLE
Unable to create read only transaction if write transaction open

### ISSUE THREAD

**Issue by DmitriyMaksimov** [leo-yuriev/libmdbx#28]
MDBX doesn't allow to open read only (MDBX_RDONLY) transaction if write transaction already open (LMDB allows that).

Code snippet to illustrate the issue:

```
MDBX_txn* txn;
int rc1 = ::mdbx_txn_begin(env, NULL, 0, &txn);

MDBX_txn* txn2;
int rc2 = ::mdbx_txn_begin(env, NULL, MDBX_RDONLY, &txn2); //<< return MDBX_BUSY
```

The behavior introduced by [commit 6b55333](https://github.com/leo-yuriev/libmdbx/commit/6b5533338fe0ffdb4a24077f885e16bfdf1ef881).

**Comment by leo-yuriev** [comment]
This is a bug (unchecked precondition) in LMDB, but not MDBX.

One thread - one transaction, otherwise you could break a lot.
Exactly `lmdb.h` say:
>  - A thread can only use one transaction at a time, plus any child
>    transactions.  Each transaction belongs to one thread.  See below.
>    The #MDB_NOTLS flag changes this for read-only transactions.
 
P.S. Sorry for typos, I write from phone.

**Comment by DmitriyMaksimov** [comment]
@leo-yuriev Большое спасибо за быстрый ответ, Леонид!
Если это баг LMDB, то наблюдается непоследовательное поведение - если поменять порядок создания транзакций (сначала открыть MDBX_RDONLY, а затем транзакцию для записи - ниже пример), то все работает. "Читающая" транзакция изолирована от "пишущей" - изменения не видны до момента фиксации (commit) и обновления (reset/renew) "читателя".

```
MDBX_txn* txn2;
int rc2 = ::mdbx_txn_begin(env, NULL, MDBX_RDONLY, &txn2); //<< возращает MDBX_OK

MDBX_txn* txn;
int rc1 = ::mdbx_txn_begin(env, NULL, 0, &txn); //<< тоже возращает MDBX_OK
```
из документации LMDB:

> There can be multiple simultaneously active read-only transactions but only one that can write. Once a single read-write transaction is opened, all further attempts to begin one will block until the first one is committed or aborted. This has no effect on read-only transactions, however, and they may continue to be opened at any time.

не совсем ясно что имеется в виду под "This has no effect on read-only transactions, however, and they may continue to be opened at any time" - понятно, что только одна транзакция может писать, но не ясно что случится если открыть "читателя" при активном "писателе". LMDB позволяет это сделать (как Вы написали это баг и MDBX_NOTLS не меняет это поведение). MDBX это не позволяет, **однако** можно открыть "писателя" при активном "читателе".

**Comment by leo-yuriev** [comment]
Вы правы насчёт непоследовательности.
Контроля для обратного порядка сейчас нет, так как он дороже - нужно просканировать всю таблицу читателей.

У Говарда в LMDB (видимо) не должно быть проблем, если не открыть и не закрывать DBI-хендлы в таких наложенных транзакциях.

У меня в MDBX проблем должно быть ещё меньше - в проблемных ситуациях должна возвращаться ошибка вместо крэша.
Однако, за ненадобностью я этого не проверял.

В целом проверка была добавлена для устранения "проблем" у некоторых пользователей, когда они путали транзакции и/или забывали их закрывать.

Необходимость в таком наложении транзакций мне совсем не очевидна.
Поэтому проще запретить такую ситуацию, нежели тестировать и обеспечивать поддержку в дальнейшем.

В будущих версиях я (пока) не собираюсь этого менять.
Но при открытии базы будет задаваться уровень контроля.
Соответственно, при включении полного контроля поведение всегда будет одинаковым  - наложение транзакций в одном потоке будет считаться ошибкой.

**Comment by DmitriyMaksimov** [comment]
Спасибо за ответ!

В нашем проекте мы используем LMDB, но не хватает произодительности при синхронной записи, а использование небезопасного режима оборачивается битой БД. Я сейчас пробую использовать MBDX, но столкнулся с описанной проблемой - один из тестов не проходит (у нас есть своя С++ обертка над LMDB). Не факт, что в прикладном коде есть такое использование, но в тестах есть...

Еще раз спасибо за ответ и за отличную работу - Ваши улучшения впечатляют!

**Comment by leo-yuriev** [comment]
Тогда внимательно прочитайте readme и при необходимости задавайте вопросы. Но в целом важно понимать, что в LMDB/MDBX всегда линейная история поэтому объем записи на диск не меняется.

Соответственно, MDBX не будет быстрее, но сохранит базу за счёт отката к последней полностью зафиксированной транзакции.
