### ISSUE TITLE
Tag a (new) Release

### ISSUE THREAD

**Issue by haneefmubarak** [leo-yuriev/libmdbx#29]
Hey @leo-yuriev,

I'd like to use this as a vendored dep in a project, but the last release was eons of commits ago. Could you tag a release at the latest point that you think feels reasonable? It'd be great to be able to refer to a proper tagged release as opposed to just pulling HEAD or some random commit hash.

Thanks!

**Comment by leo-yuriev** [comment]
@haneefmubarak, just now I tagget [v0.1.0](https://github.com/leo-yuriev/libmdbx/releases/tag/v0.1.0)
