### ISSUE TITLE
Docs/question: What are the intended/optimized-for use cases for the next version?

### ISSUE THREAD

**Issue by 0joshuaolson1** [leo-yuriev/libmdbx#30]
- I see mdbx targets more than POSIX platforms (not reflected the README?), so it's not going to be limited to/optimized for a specific kernel's memory management style?
- If I just want a sparse/hash set, does that affect some limit on the number of keys in the database?
- What is it not designed/good for? Highly parallel writes? Larger-than-RAM random-access reads?

**Comment by leo-yuriev** [comment]
>  I see mdbx targets more than POSIX platforms (not reflected the README?), so it's not going to be limited to/optimized for a specific kernel's memory management style?
1. Support for other OS could be added, but I don't have infrastructure and enough time to do this. For instance public and free CI-services are available for Linux and Windows, but not for FreeBSD, AIX, Solaris, QNX and so on. +https://github.com/leo-yuriev/libmdbx/commit/ae708aab134c10b310f32b2962fc283ef746bfe0
2. One of an important point of MDBX/LMDB design is to avoid any internal memory management, including optimization/cheats for specific OS.

> If I just want a sparse/hash set, does that affect some limit on the number of keys in the database?
As noted in the readme MDBX provides only order maps, which implemented over B+tree of pages, that mapped from DB-file into RAM. Therefore:
  - 'sparse set' is not possible.
  - number of keys limited by DB size and the summary size of each record.

Actually maximal DB size on 64-bit platforms limited by RAM and/or disk space.
On 32-bit platform actually limit is near to half of 32-bit address space, but only 0x38000000 for Windows 
See https://github.com/leo-yuriev/libmdbx/blob/master/src/bits.h#L390-L398

> What is it not designed/good for? Highly parallel writes? Larger-than-RAM random-access reads?
All the necessary information is already in README, but its understanding requires some background and knowledge of terminology (e.g. RAF and WAF and so on).

As noted in the readme:
  - MDBX allows only a single writer at any moment, no more. In other words writes are strongly serialized, i.e. parallel writes are not possible.
  - all data just mapped into RAM, therefore Larger-than-RAM cases will give a RAF-corresponding swapping via OS's virtual memory mechanism.

Please read https://github.com/leo-yuriev/libmdbx#comparison-with-other-dbs an follow the link.
