### ISSUE TITLE
Any plans to make bindings for other langs?

### ISSUE THREAD

**Issue by byaka** [leo-yuriev/libmdbx#35]
Крайне интересный и многообещающий форк LMDB!

А планируется ли в ближайшем будущем сделать биндинги для других языков (например для python)?
Пытаюсь привлечь [https://python-forum.io/Thread-libmdbx-prod-ready-fork-of-LMDB-someone-can-wrap-it-for-python?pid=50151#message](сообщество), ибо прекрасно понимаю, что биндинги не входят в число приоритетов. Но боюсь, что ничего не выйдет - для оригинального LMDB биндингов мало, они по большей части неподдерживаемые или "на грани".

**Comment by leo-yuriev** [comment]
Это планируется сделать для версии 1.0, которая сейчас в ветке [devel](https://github.com/leo-yuriev/libmdbx/tree/devel).

**Comment by byaka** [comment]
спасибо, рад слышать :)
