### ISSUE TITLE
Database corruption by cross-merging LEAF and BRANCH pages (inherited from LMDB)

### ISSUE THREAD

**Issue by leo-yuriev** [leo-yuriev/libmdbx#38]
This bug discovered by long-running test, which add/update/delete key-value pairs with stochastically choosing the length of key and data.

Running such test with quantity of transaction in range from 100,000 to 1,000,000 fails with a probability of about 0.1 - 1%.

The investigation showed that the damage to the database structure is due to erroneous / invalid merging of different types of pages, i.e. mering LEAF into BRANCH or BRANCH into LEAF.

**Comment by leo-yuriev** [comment]
Это одна из фатальных ошибок унаследованных из LMDB - существенное упущение в дизайне и алгоритмах, которое замаскированно плохим стилем кодирования.

Суть проблемы:
 - высота дерева может увеличиваться даже при удалении данных (пояснение ниже).
 - в коде пере-балансировке и слияния несть несколько ошибок/упущений, но увеличения высоты дерева приводит к разрушению БД из-за вот этого [ребус-кошмара в LMDB](https://github.com/LMDB/lmdb/blob/26c7df88e44e31623d0802a564f24781acdefde3/libraries/liblmdb/mdb.c#L9070-L9078).

Рост дерева возможен при существенном различии/разбросе длины ключей:
 - в каждой не-листовой странице дерева содержаться записи-указатели на дочерние страницы.
 - каждая такая запись состоит из номера дочерней страницы и ключа, значение которого является наименьшим из всех дочерних записей.
 - более того, в качестве оптимизации для экономии места, ключ первой записи дочерней страницы часто не храниться, так как совпадает с ключом в записи-указателе на родительской странице.

Соответственно, если при вставке/удалении на странице меняется значение ключа у первой записи, то это изменение должно быть вытолкнуто в родительскую страницу, и при необходимости рекурсивно до корня дерева.

Однако, при таком обновлении, новое значение ключа может быть существенно длиннее предыдущего из-за чего на родительской странице может не хватить места. В том числе такое может быть при удалении.

Например, если было две записи {key="a", value="x"} и {key="bbb...bbb", value="y"} и мы удаляем первую, то в родительской странице короткий ключ "a" должен быть заменен на длинный "bbb...bbb".

Если на родительской странице не хватает места, то она должна быть разделена. В свою очередь, это потребует вставки в её родительскую страницу, и в ней тоже может не быть места, и так далее.

В результате, удаление может привести к увеличению высоты дерева страниц и LMDB уничтожит ваши данные.

**Comment by hyc** [comment]
Sounds like http://www.openldap.org/its/index.cgi/Software%20Bugs?id=8258

**Comment by leo-yuriev** [comment]
Yes @hyc , this is the same bug/issue, but it newer has been fixed (corresponding ITS-patch is applied a time ago).

Briefly, independent of merge-or-move strategy it is possible that a tree will be higher after the deletion than the before.

**Comment by leo-yuriev** [comment]
Testcase is simple:
 - let S is a sequence of 3-byte long numbers (e.g 0...2^24-1).
 - insert a lot of "even" items with short keys of form "aS".
 - insert a lot of "odd" items with long keys of form "bS-any-long-string-upto-maxkeylength".
 - remove an "even" items.

**Comment by hyc** [comment]
By "odd" and "even" do you mean the long and short keys are interleaved? Otherwise I don't see how this can trigger the issue.

**Comment by leo-yuriev** [comment]
Yes, certainly.
It seems obvious .

**Comment by hyc** [comment]
Unable to reproduce any failure...

[mtest7.c.txt](https://github.com/leo-yuriev/libmdbx/files/2361800/mtest7.c.txt)

**Comment by leo-yuriev** [comment]
I tried the given [mtest7](https://github.com/leo-yuriev/lmdb/commit/20f1eb4dc4d0a00a5680ca41c6435993ac49d4bf) and then made [some changes](https://github.com/leo-yuriev/lmdb/commit/b2999d143da6d599190edd13a067a8b2362a00bd) to fit the scenario I tried to describe above.

Unfortunately it don't reproduce the failure nor in the original LMDB, nor in the MDBX.
However, a longer stochastic test steadily reproduces the problem in the MDBX.
This test currently couldn't be run with LMDB, i.e. a lot of API-related changes are required.

On the other hand, it looks like I'm close to fixing the problem in MDBX.
With my current fixes, the database was never corrupted due relabalance itself, but in complex cases, the cursor position becomes invalid after deletion.
In other words, the page stack of the cursor becomes invalid after deletion, in some cases when the tree grows due to rebalancing.

I expect to complete the work within a week. After that, we can try to adapt the stochastic test for LMDB and check if there is this problem.

**Comment by leo-yuriev** [comment]
Fixed in the 'master' branch now.
