### ISSUE TITLE
Rename to "Mithril DB"?

### ISSUE THREAD

**Issue by leo-yuriev** [leo-yuriev/libmdbx#57]

**Comment by 0x4E69676874466F78** [comment]
Why exactly Metal?
If you nonetheless rename it do not forget to leave a mark (ex libmdbx) to after reindexing (search engines) can still be found by the old name.

**Comment by vladp** [comment]
when naming, you, unfortunately, need to check for large-sized projects/initiatives that might share this name.
in this case Metal is https://developer.apple.com/metal/

Larger projects will overshadow/confuse programmers.
Probably not something you want.

Еще есть один небольшой совет (если можно):

я не уверен что постоянное напоминание насколько Ваше решение лучше лмдб -- очень помогает.  Может лучше показать benchmark со несколькими похожими решениями, и лмдб, в том числе, может быть одним из сравнений

тк у Вас API compatible, может быть лушче упомянуть как комплимент лмдб -- что лмдб interfaces полностью поддерживаются, и помогают Вашему решению участвовать в обширной экосистеме лмдб клиентов.

**Comment by ddorian** [comment]
In this case `metal` is not a db, so it should be ok. As long as you search with `db`, like `lmdb`, `rocksdb`, `leveldb`.

**Comment by leo-yuriev** [comment]
> Еще есть один небольшой совет (если можно):
> 
> я не уверен что постоянное напоминание насколько Ваше решение лучше лмдб -- очень помогает. Может лучше показать benchmark со несколькими похожими решениями, и лмдб, в том числе, может быть одним из сравнений

Не пойму о чем вы говорите. Объективно есть ряд доработок, которые просто перечислены в README с небольшими пояснениями. А в актуальной версии README, в самом начале есть фразе _"libmdbx превосходит LMDB по возможностям и надежности, не уступая в производительности"_, которая достаточно точно и кратко передает суть.

Далее, в README также есть результаты бенчмарков и сравнение "с несколькими похожими решениями", включая краткое описание сценариев и ссылки на скрипты и исходный код теста.

Сравнения производительности с LMDB (пока) нет по ряду причин:
 - Код MDBX и LMDB (сейчас) одинаково оптимален, поэтому разница определяется поведением и взаимодействием с ОС (например из-за файловых блокировок на Windows).
 - Поведение MDBX отличается из-за добавленных возможностей (LIFO и т.д.) и явно измененного взаимодействия (гарантии сохранности данных, файловые блокировки на Windows).

Поэтому сравнение LMDB c MDBX сводиться к трем случаям:
 - на Windows LMDB будет чуть быстрее _только_ в сценариях "много мелких пишущих транзакций в не-SYCN режиме" из-за того, что MDBX использует более надежные (защищающие от дурака) файловые блокировки.
 - MDBX будет _всегда_ быстрее (может даже в разы) при включении MDBX_LIFO_RECLAIM в сценариях "много мелких пишущих транзакций в SYNC-режиме" на системах с write-back очередью/кешем диска.
 - в остальных случаях производительность будет отличаться в пределах погрешности, с поправкой на то, что MDBX может быть чуть медленнее в сильно искусственных сценариях из массы очень простых операций (итерирование курсором) из-за дополнительных проверок в коде (основной оверхед в вызове pthread_self() при проверке что вызывающих тред пользуется своей транзакцией, а не чужой).

> тк у Вас API compatible, может быть лушче упомянуть как комплимент лмдб -- что лмдб interfaces полностью поддерживаются, и помогают Вашему решению участвовать в обширной экосистеме лмдб клиентов.

Совместимости по API c LMDB нет. При первом взгляде это кажется минусом и фасад для "бесшовной" стыковки выглядит неплохой идеей.
Однако есть подводные камни:
 -  В libmdbx у курсоров одинаковое время жизни, а в LMDB по-разному в зависимости от ситуации. Это сознательное изменение API для ухода от ряда проблем.
 - В libmdbx другое время жизни DPI-хендлов. Это также сознательное изменение внутренних механизмов для ухода от ряда проблем.
 - Масса более мелких различий в поведении функций (более ожидаемое поведение и недопущение "хаков" ведущих к ошибкам).

Поэтому "фасад LMDB" не может быть полностью совместимым c LMDB - и зачем он тогда нужен. Кроме этого, если не нужны дополнительные возможности libmdbx, то зачем уходить с LMDB?

Тем не менее, я соглашусь с тем, что в REAME стоит добавить абзац по теме миграции c LMDB.

**Comment by leo-yuriev** [comment]
s/Meta/[Mithril](https://en.wikipedia.org/wiki/Mithril)/g ?

> Mithril is ... described as resembling silver but being stronger and lighter than steel.

**Comment by ddorian** [comment]
any eta for Mithril ? Or how does it differ ?
