### ISSUE TITLE
About the relocation function

### ISSUE THREAD

**Issue by Kerollmops** [leo-yuriev/libmdbx#65]
Did you though about implementing the currently [unimplemented LMDB `mdb_set_relfunc`](http://www.lmdb.tech/doc/group__mdb.html#ga697d82c7afe79f142207ad5adcdebfeb)?

I though about that because in Rust (and probably a whole lot other languages) interpreting a type that is not correctly aligned is undefined behavior, therefore when reading entries from LMDB/MDBX we need to check the alignment and reallocate the data if badly aligned. With this reallocation feature on the database side it would have been way easier to deal with alignment.

**Comment by leo-yuriev** [comment]
`MDB_rel_func` is for another and will not help in any way to data alignment.

However, it's easy to get aligned with _libmdbx_ right now:
- for a particular sub-database, ensure that all keys and values are a multiple of the required alignment;
- don't use `MDBX_DUPSORT` if the required alignment is greater than 4.

This should work basically, although I don't have any ready tests to check it.

---

I will definitely not add such a feature to _libmdbx_, as it will require changing the database file format. However, However, I will consider this when implementing _MithrilDB_.

**Comment by Kerollmops** [comment]
[Here is the source of my though about the fact that this function would help on memory alignment](https://github.com/AltSysrq/lmdb-zero/issues/8).

**Comment by leo-yuriev** [comment]
@Kerollmops, unfortunately I made a mistake (leading parallel development of libmdbx and MithrilDB I begin to confuse their behavior).

So, _libmdbx_ can _only_ provide 4-byte alignment if the length of all keys and values is a multiple of 4.
