### ISSUE TITLE
non-WRITEMAP mode is broken on OpenBSD (this is OpenBSD kernel's bug)

### ISSUE THREAD

**Issue by leo-yuriev** [leo-yuriev/libmdbx#67]
On OpenBSD writing to the file descriptor of a mmap'ed file are not (always and/or immediately) visible in the corresponding mmap'ed memory region.

For this reason:
 - all tests in modes with the WRITEMAP flag are always passed.
 - otherwise (in modes without the WRITEMAP flag) most tests fails with very high probability.

**Comment by leo-yuriev** [comment]
It's Not a Bug, It's a [OpenBSD's Feature](https://marc.info/?l=openbsd-bugs&m=157373953304874&w=2).

**Comment by leo-yuriev** [comment]
Related topic https://www.linux.org.ru/forum/development/15346691

**Comment by leo-yuriev** [comment]
@hyc, FYI for LMDB.

**Comment by hyc** [comment]
This was always known. OpenBSD has no unified buffer cache http://www.openldap.org/lists/openldap-technical/201708/msg00010.html
