### ISSUE TITLE
Opening a txn fails if env was opened with MDBX_NOTLS

### ISSUE THREAD

**Issue by snej** [leo-yuriev/libmdbx#72]
I'm porting some LMDB-based code to libmdbx, but hitting an assertion failure as soon as I open the first transaction. This looks like it might be a mistake in an assertion in the library.

My code is equivalent to:
```c++
        mdbx_env_create(&_env);
        mdbx_env_set_userctx(_env, this);
        mdbx_env_set_maxdbs(_env, 20);
        mdbx_env_open(_env, string(path).c_str(), MDBX_NOTLS, 0600);
        mdbx_txn_begin(_env, nullptr, MDBX_RDONLY, &_txn);
```
This last line triggers an assertion failure at core.c line 5322:
```c
    mdbx_assert(env, (txn->mt_flags &
                      ~(MDBX_RDONLY | MDBX_WRITEMAP | MDBX_SHRINK_ALLOWED |
                        MDBX_NOMETASYNC | MDBX_NOSYNC | MDBX_MAPASYNC)) == 0);
```
At the time, `txn->mt_flags` is `MDBX_NOTLS | MDBX_RDONLY`.

My hypothesis is that the transaction inherits the flags of the environment, but the assertion does not consider the possibility that the environment is opened with `MDBX_NOTLS`. I experimentally added `MDBX_NOTLS` to the list of flags in the assertion, and the failure went away (now I'm failing somewhere farther on...)

My checkout of liblmdbx is at commit 61d2e07cf0cd65aa61fbc34c1806f412c3fe63b6.

**Comment by snej** [comment]
The issue persists in the latest commit on master, 2acaaeb2ff98c7baa67836636ac3b2cf8c079a36. My workaround seems good, since (after some fixes to my code) my entire program is now running.

**Comment by leo-yuriev** [comment]
@snej, thank you for report. I will fix this shortly.
