### ISSUE TITLE
Sparse file support (mark garbage pages as "holes")

### ISSUE THREAD

**Issue by snej** [leo-yuriev/libmdbx#74]
Some filesystems allow page-bounded regions of a file to be "holes" that look as though they're filled with zeroes but actually occupy no disk space. This is of course ideal for free space in a db file.

The last few releases of macOS and iOS have a new filesystem (APFS) that supports this. Holes are created by calling `fcntl(fd, F_PUNCHHOLE, ...)`. It would be great if libmdbx would support this, as it would nearly eliminate wasted space in databases, without compaction.

The drawback is that overwriting a hole can cause a disk-full error even if the file doesn't grow, which isn't otherwise possible, so there may be some new edge cases to handle with nearly-full volumes.

(I know some Linux filesystems support this too, but I don't know the API. I think it's different, since googling for "F_PUNCHHOLE" turned up only Mac and iOS-related info.)

**Comment by leo-yuriev** [comment]
This is unreasonable. Sure.

1. Holes are (relatively) expensive:
   - creating each hole requires syscall and adding / updating internal FS structures (via journal, etc), moreover immediate PTE invalidation.
   - for mmap-region each hole has more expensive page-fault (i.e. FS space allocation) and/or requires tracking.
2. For B+Tree we will have a random pattern of single-pages holes, i.e. large and finely chopped file-allocation list, which would be updated on each hole-creation and hole-deletion.
3. For mostly cases pages could be released / recycled not at the time it puts into GC lists (at transaction was committed), but later when all readers will complete its read transactions. Therefore hole creation requires additional post-processing.

_libmdbx_ already performs aggressively "hot compactification" (pages deallocation at end of region with subsequent file truncation). Therefore, in view of the above, I do not consider the requested feature useful and/or reasonable.
