### ISSUE TITLE
Coverity scan workaround seems to be not needed anymore

### ISSUE THREAD

**Issue by sowle** [leo-yuriev/libmdbx#81]
It seems that Coverity scan workaround introduced by commit b4434778697628e159a5f59c89b19557703efaf4 is causing issues with the most recent Coverity 2019.03 as they have fixed this issue on their side and two workarounds conflict:

```
1. bad_type_name_redeclaration: invalid redeclaration of type name "_Float32x" (declared at line 2578 of "build/cov-int/emit/Ubuntu-1804-bionic-64-minimal/config/fa74efd3630a99ecd0aa23c5fea9b8b8/gcc-config-0/coverity-compiler-compat.h")
```

I have just tried to comment out the whole block `/* Workaround for Coverity Scan */` in `defs.h` and it went okay with the Coverity 2019.03.

**Comment by leo-yuriev** [comment]
Thank you for reporting it.
